openapi: "3.0.3"
info:
  title: "Data"
  version: "1.0.0"

servers:
  - url: 'https://documentation.staircaseapi.com/persistence'
paths:
  /transactions/{transaction_id}/collections/{collection_id}:
    get:
      tags:
        - Collections
      summary: "Retrieve Collection"
      description: "Retrieve Collection"
      operationId: "get_collection"
      parameters:
      - $ref: 'https://raw.githubusercontent.com/StaircaseAPI/shared_definitions/main/yaml/parameters.yaml#/parameters/transactionIdPathRequired'
      - $ref: 'https://raw.githubusercontent.com/StaircaseAPI/shared_definitions/main/yaml/parameters.yaml#/parameters/collectionIdPathRequired'
      - name: "refs"
        in: "query"
        description: "If `true` refs will not be resolved"
        required: false
        schema:
          "type": "boolean"
      responses:
        '200':
          $ref: "https://raw.githubusercontent.com/StaircaseAPI/shared_definitions/main/yaml/responses.yml#/responses/200CollectionCreated"